version: '3'

services:
  backend:
    build: .
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=dev_db
      - MYSQL_USER=dev_user
      - MYSQL_PASSWORD=dev_pass
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
